development:
  adapter: postgresql
  database: db/dev_database
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/test_database
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production_database
  pool: 5
  timeout: 5000